import {test,expect} from '@playwright/test';
import ExcelJS from 'exceljs';
test('primeiro acesso, fornecedor, item, duas cotações, pagamento, Excel e outro dispositivo',async({page,browser})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByLabel('E-mail',{exact:true}).fill('admin@example.test');await page.getByLabel('Senha',{exact:true}).fill('SenhaDeTeste123!');
 await page.getByLabel('Chave do primeiro acesso',{exact:true}).fill(process.env.SETUP_KEY);
 await page.getByRole('button',{name:'Criar administrador',exact:true}).click();
 let modal=page.getByRole('dialog',{name:'Definir ano das formaturas',exact:true});await expect(modal).toBeVisible();
 await modal.getByLabel('Ano *',{exact:true}).fill('2028');await modal.getByRole('button',{name:'Salvar ano',exact:true}).click();await expect(modal).not.toBeVisible();
 await page.getByRole('navigation').getByRole('button',{name:'Fornecedores',exact:true}).click();
 await page.getByRole('button',{name:'Cadastrar fornecedor',exact:true}).first().click();
 modal=page.getByRole('dialog',{name:'Cadastrar fornecedor',exact:true});
 await modal.getByLabel('Empresa ou profissional *',{exact:true}).fill('Fornecedor de teste A');await modal.getByLabel('Pessoa de contato',{exact:true}).fill('Contato de teste');
 await modal.getByLabel('Telefone/WhatsApp',{exact:true}).fill('(49) 99999-9999');await modal.getByLabel('Cidade',{exact:true}).fill('Fraiburgo');
 await modal.getByRole('button',{name:'Salvar',exact:true}).click();await expect(modal).not.toBeVisible();
 await page.getByRole('navigation').getByRole('button',{name:/Eventos/}).click();
 await page.locator('.event-card').filter({hasText:'Bombeiro Mirim'}).getByRole('button',{name:'Abrir evento'}).click();
 await page.getByRole('button',{name:'Adicionar item',exact:true}).first().click();modal=page.getByRole('dialog',{name:'Adicionar item',exact:true});
 await modal.getByLabel('Descrição do serviço ou material *',{exact:true}).fill('Locação de 200 cadeiras');
 await modal.getByLabel('Categoria',{exact:true}).selectOption({label:'Cadeiras'});
 await modal.getByLabel('Fornecedor',{exact:true}).selectOption({label:'Fornecedor de teste A · Fraiburgo'});
 await modal.getByLabel('Quantidade',{exact:true}).fill('200');await modal.getByLabel('Unidade',{exact:true}).fill('unidade');
 await modal.getByLabel('Valor unitário (R$)',{exact:true}).fill('6,50');await modal.getByRole('button',{name:'Salvar',exact:true}).click();await expect(modal).not.toBeVisible();
 await page.getByRole('button',{name:'Detalhes e cotações (1)',exact:true}).click();
 const details=page.getByRole('dialog',{name:'Detalhes do item',exact:true});await details.getByRole('button',{name:'Adicionar cotação',exact:true}).click();
 modal=page.getByRole('dialog',{name:'Adicionar cotação',exact:true});await modal.getByRole('button',{name:'Cadastrar fornecedor',exact:true}).click();
 const supplierModal=page.getByRole('dialog',{name:'Cadastrar fornecedor',exact:true});
 await supplierModal.getByLabel('Empresa ou profissional *',{exact:true}).fill('Fornecedor de teste B');await supplierModal.getByRole('button',{name:'Salvar',exact:true}).click();await expect(supplierModal).not.toBeVisible();
 await modal.getByLabel('Quantidade',{exact:true}).fill('200');await modal.getByLabel('Valor unitário (R$)',{exact:true}).fill('5,50');
 await modal.getByRole('button',{name:'Salvar',exact:true}).click();await expect(modal).not.toBeVisible();
 const chosen=details.locator('.quote-card').filter({hasText:'Fornecedor de teste B'});
 await chosen.getByRole('button',{name:'Escolher este orçamento',exact:true}).click();await expect(chosen.getByText('Escolhido',{exact:true})).toBeVisible();
 await details.getByRole('button',{name:'Editar item',exact:true}).click();modal=page.getByRole('dialog',{name:'Editar item',exact:true});
 await modal.getByLabel('Situação',{exact:true}).selectOption('Contratado');await modal.getByLabel('Valor já pago (R$)',{exact:true}).fill('0');
 await modal.getByRole('button',{name:'Salvar',exact:true}).click();await expect(modal).not.toBeVisible();
 await details.getByRole('button',{name:'Registrar pagamento',exact:true}).click();modal=page.getByRole('dialog',{name:'Registrar pagamento',exact:true});
 await modal.getByLabel('Valor deste pagamento (R$) *',{exact:true}).fill('250');await modal.getByRole('button',{name:'Registrar pagamento',exact:true}).click();await expect(modal).not.toBeVisible();
 await expect(details.getByText(/R\$\s*850,00/)).toBeVisible();await details.getByRole('button',{name:'Fechar detalhes',exact:true}).click();
 await page.getByRole('textbox',{name:'Buscar descrição ou fornecedor'}).fill('não encontra este item');
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar este evento',exact:true}).click();
 const file=await downloaded,stream=await file.createReadStream(),chunks=[];for await(const chunk of stream)chunks.push(chunk);
 const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(Buffer.concat(chunks));expect(workbook.worksheets).toHaveLength(4);
 for(const [cell,value] of [['C2',1100],['D2',1100],['E2',250],['F2',850]])expect(workbook.getWorksheet('Resumo geral').getCell(cell).value).toBe(value);
 expect(workbook.getWorksheet('Cotações').rowCount).toBe(3);
 let state=await (await page.request.get('/api/state')).json();expect(state.events).toHaveLength(4);const event=state.events[0],item=event.items[0];
 const excessive=await page.request.post('/api/mutate',{headers:{Origin:'http://localhost:3000'},data:{action:'item.pay',data:{eventId:event.id,itemId:item.id,amount:'900'},revision:state.revision}});expect(excessive.status()).toBe(400);
 const stale=await page.request.post('/api/mutate',{headers:{Origin:'http://localhost:3000'},data:{action:'setYear',data:{year:2029},revision:state.revision-1}});expect(stale.status()).toBe(409);
 const cross=await page.request.post('/api/mutate',{headers:{Origin:'https://untrusted.example'},data:{action:'setYear',data:{year:2029},revision:state.revision}});expect(cross.status()).toBe(403);
 const second=await browser.newContext({viewport:{width:390,height:844}}),phone=await second.newPage();
 expect((await phone.request.get('http://localhost:3000/api/export')).status()).toBe(401);
 await phone.goto('http://localhost:3000/');await phone.getByLabel('E-mail',{exact:true}).fill('admin@example.test');await phone.getByLabel('Senha',{exact:true}).fill('SenhaDeTeste123!');
 await phone.getByRole('button',{name:'Entrar',exact:true}).click();await expect(phone.getByRole('heading',{name:'Visão geral',exact:true})).toBeVisible();
 await expect(phone.locator('.event-card')).toHaveCount(4);expect(await phone.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await phone.locator('.event-card').filter({hasText:'Bombeiro Mirim'}).getByRole('button',{name:'Abrir evento'}).click();
 await expect(phone.locator('.mobile-item').filter({hasText:'Locação de 200 cadeiras'})).toBeVisible();
 await phone.screenshot({path:'test-results/mobile-evento.png',fullPage:true});
 await phone.getByRole('button',{name:'Sair',exact:true}).click();await expect(phone.getByRole('button',{name:'Entrar',exact:true})).toBeVisible();
 await page.getByRole('textbox',{name:'Buscar descrição ou fornecedor'}).fill('');
 // Uma edição inline confirma o salvamento no banco.
 const description=page.getByRole('textbox',{name:'Descrição de Locação de 200 cadeiras'});
 await description.fill('Locação de 200 cadeiras confirmada');await description.press('Enter');
 await expect(page.getByRole('textbox',{name:'Descrição de Locação de 200 cadeiras confirmada'})).toBeVisible();
 await page.getByRole('navigation').getByRole('button',{name:'Visão geral',exact:true}).click();
 const allDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar todos os eventos',exact:true}).click();
 const allFile=await allDownload,allStream=await allFile.createReadStream(),allChunks=[];for await(const chunk of allStream)allChunks.push(chunk);
 const allBook=new ExcelJS.Workbook();await allBook.xlsx.load(Buffer.concat(allChunks));expect(allBook.worksheets).toHaveLength(7);
 await page.screenshot({path:'test-results/visao-geral.png',fullPage:true});await page.reload();await expect(page.locator('.event-card')).toHaveCount(4);
 state=await (await page.request.get('/api/state')).json();expect(state.events[0].items[0].description).toBe('Locação de 200 cadeiras confirmada');
 expect(errors).toEqual([]);await second.close();
});
