'use client';
import {useState,useEffect,useRef} from 'react';
import {GraduationCap,LayoutDashboard,CalendarDays,Users,Plus,Download,ChevronRight,ArrowLeft,Search,Settings2,LogOut,Wallet,CheckCircle2,Clock3,ClipboardList,FileSpreadsheet,Pencil,Copy,Trash2,Info,ShieldCheck,LoaderCircle,X,Check} from 'lucide-react';
import {Button,Badge,Field,Empty,Modal,FormDialog} from './ui';
import {SupplierForm,ItemForm,QuoteForm,EventForm,CategoryForm,YearForm,PayForm} from './Forms';
import {money,summarize,dateText,categorySummary,selected,quoteTotal,centsInput,quantityInput,STATUSES,isActive} from '../lib/domain';
async function request(path,options={}){
 const response=await fetch('/api/'+path,{cache:'no-store',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});
 let data;try{data=await response.json();}catch{throw new Error('O servidor não respondeu como esperado. Tente novamente.');}
 if(!response.ok){const e=new Error(data.error||'Não foi possível concluir.');e.status=response.status;throw e;}return data;
}
function Auth({auth,onAuthenticated,onRetry,error:initialError}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const setup=auth&&!auth.initialized;
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await request(setup?'auth/setup':'auth/login',{method:'POST',body:JSON.stringify({email,password,setupKey:key})});await onAuthenticated(r.user);}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <div className="auth-page"><div className="auth-brand"><GraduationCap size={32}/><span>Organização de<br/><strong>Formaturas</strong></span></div>
 <div className="auth-card"><div className="auth-symbol"><ShieldCheck size={30}/></div><h1>{setup?'Configure seu primeiro acesso':'Bem-vindo de volta'}</h1><p>{setup?'Crie o administrador para começar a organizar suas formaturas.':'Entre para acessar seus eventos, fornecedores e orçamentos.'}</p>
 {initialError?<><div className="notice danger" role="alert">{initialError}</div><Button onClick={onRetry}>Tentar novamente</Button></>:<form onSubmit={submit}>
 <Field label="E-mail"><input autoFocus type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com"/></Field>
 <Field label="Senha" hint={setup?'Use pelo menos 10 caracteres.':undefined}><input type="password" minLength={setup?10:undefined} maxLength={200} autoComplete={setup?'new-password':'current-password'} required value={password} onChange={e=>setPassword(e.target.value)} placeholder={setup?'Crie uma senha segura':'Digite sua senha'}/></Field>
 {setup&&<Field label="Chave do primeiro acesso" hint="Use a chave SETUP_KEY definida na hospedagem. Ela é solicitada somente neste primeiro cadastro."><input type="password" required autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Cole a chave de configuração"/></Field>}
 {error&&<div role="alert" className="notice danger">{error}</div>}<Button type="submit" className="full-width" disabled={busy}>{busy&&<LoaderCircle size={18} className="spin"/>}{busy?'Aguarde…':setup?'Criar administrador':'Entrar'}</Button>
 </form>}</div><p className="auth-note">Tudo organizado para celebrar grandes conquistas.</p></div>;
}
function Amount({value,partial=false}){return <span className="amount">{money(value)}{partial&&<small className="partial">Parcial</small>}</span>;}
function Metrics({events}){
 const t=summarize(events),metrics=[['Total previsto',t.expected,t.expectedPartial,ClipboardList,'Orçamentos escolhidos'],['Total contratado',t.contracted,false,CheckCircle2,t.contractedCount+' itens contratados'],['Total pago',t.paid,t.paidPartial,Wallet,'Pagamentos dos contratados'],['Saldo a pagar',t.balance,t.balancePartial,Clock3,'Dos serviços contratados']];
 return <div className="metrics">{metrics.map(([label,value,partial,Icon,help],i)=><div className={'metric metric-'+i} key={label}><div className="metric-label"><span>{label}</span><Icon size={19}/></div><Amount value={value} partial={partial}/><small>{help}</small></div>)}</div>;
}
function EventCard({event,open}){
 const t=summarize(event);
 return <article className={'event-card accent-'+event.color}><div className="event-card-top"><div className="event-symbol"><GraduationCap size={22}/></div><span className="date-chip"><CalendarDays size={14}/>{dateText(event)}</span></div>
 <h3>{event.name}</h3><div className="event-expected"><span>Total previsto</span><Amount value={t.expected} partial={t.expectedPartial}/></div>
 <dl className="event-finances"><div><dt>Contratado</dt><dd>{money(t.contracted)}</dd></div><div><dt>Pago{t.paidPartial?' (parcial)':''}</dt><dd>{money(t.paid)}</dd></div><div><dt>Saldo a pagar{t.balancePartial?' (parcial)':''}</dt><dd>{money(t.balance)}</dd></div></dl>
 <div className="event-progress"><span>{event.categories.length-t.undefinedCategories} de {event.categories.length} categorias definidas</span><div><i style={{width:(100*(event.categories.length-t.undefinedCategories)/Math.max(1,event.categories.length))+'%'}}/></div></div>
 <div className="event-card-footer"><span>{t.undefinedCategories?t.undefinedCategories+' sem definição':'Tudo definido'}</span><Button variant="text" onClick={()=>open(event.id)}>Abrir evento<ChevronRight size={17}/></Button></div></article>;
}
function Overview({ctx,open,exportExcel}){
 const {state}=ctx,names=[...new Set(state.events.flatMap(e=>e.categories.map(c=>c.name)))];
 return <><div className="page-heading"><div><div className="eyebrow">PLANEJAMENTO E CUSTOS</div><h1>Visão geral</h1><p>Acompanhe cada detalhe das suas formaturas.</p></div><div className="export-wrap"><Button variant="secondary" onClick={()=>exportExcel()} disabled={ctx.exporting}><Download size={17}/>{ctx.exporting?'Exportando…':'Exportar todos os eventos'}</Button><small>Inclui todos os registros, mesmo os fora da tela.</small></div></div>
 {!state.defaultYear&&<div className="year-banner"><div className="banner-icon"><CalendarDays size={22}/></div><div><strong>Falta definir o ano das formaturas</strong><p>Os dias e meses já estão cadastrados. Informe o ano para completar as datas.</p></div><Button variant="secondary" onClick={()=>ctx.setDialog({type:'year'})}>Definir ano</Button></div>}
 <Metrics events={state.events}/><div className="section-heading"><h2>Suas formaturas <span className="count">{state.events.length}</span></h2><Button variant="text" onClick={()=>ctx.setDialog({type:'event'})}><Plus size={16}/>Cadastrar evento</Button></div>
 <div className="event-grid">{state.events.map(e=><EventCard key={e.id} event={e} open={open}/>)}</div>
 <section className="panel comparison"><div className="panel-heading"><div><h2>Resumo por categoria</h2><p>Clique em uma categoria para preencher ou consultar os itens.</p></div><FileSpreadsheet size={22}/></div>
 <div className="table-scroll"><table className="matrix"><thead><tr><th>Evento</th><th>Data</th>{names.map(n=><th key={n}>{n}</th>)}<th>Total previsto</th></tr></thead><tbody>{state.events.map(e=><tr key={e.id}><th scope="row"><button className="plain-link" onClick={()=>open(e.id)}>{e.name}</button></th><td className="nowrap">{dateText(e)}</td>{names.map(n=>{const c=e.categories.find(c=>c.name===n),s=c?categorySummary(e,c):null;return <td key={n}>{s?<button className="matrix-cell" onClick={()=>open(e.id,c.id)}><span>{money(s.value)}</span><Badge>{s.status}</Badge>{s.partial&&s.value!==null&&<small>Valor parcial</small>}</button>:<span className="subtle">Não cadastrada</span>}</td>;})}<td><Amount value={summarize(e).expected} partial={summarize(e).expectedPartial}/></td></tr>)}</tbody></table></div>
 <div className="panel-footnote"><Info size={15}/><span>Totais parciais consideram somente os valores informados. O contratado já faz parte do previsto.</span></div></section></>;
}
function InlineDescription({item,onSave,busy}){
 const [value,setValue]=useState(item.description),cancel=useRef(false);useEffect(()=>setValue(item.description),[item.description]);
 return <input className="inline-input" aria-label={'Descrição de '+item.description} value={value} disabled={busy} onChange={e=>setValue(e.target.value)}
 onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){cancel.current=true;setValue(item.description);e.currentTarget.blur();}}}
 onBlur={async()=>{if(cancel.current){cancel.current=false;return;}if(value!==item.description){try{await onSave(value);}catch{setValue(item.description);}}}}/>;
}
function EventDetail({event,category,setCategory,ctx,back,exportExcel}){
 const [search,setSearch]=useState(''),[status,setStatus]=useState('');
 const supplierFor=i=>ctx.state.suppliers.find(s=>s.id===selected(i)?.supplierId);
 const filtered=event.items.filter(i=>(!category||i.categoryId===category)&&(!status||i.status===status)&&[i.description,supplierFor(i)?.name??''].join(' ').toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
 const groups=event.categories.filter(c=>!category||c.id===category),edit=i=>ctx.setDialog({type:'item',eventId:event.id,itemId:i.id}),details=i=>ctx.setDetail({eventId:event.id,itemId:i.id});
 async function simpleSave(i,change){try{return await ctx.act('item.save',{eventId:event.id,id:i.id,categoryId:i.categoryId,description:i.description,unit:i.unit,status:i.status,notes:i.notes,paid:centsInput(i.paidCents),...change});}catch(e){ctx.notify(e.message,'error');throw e;}}
 return <><Button variant="text" className="back-button" onClick={back}><ArrowLeft size={16}/>Todos os eventos</Button>
 <div className="page-heading"><div><div className="eyebrow">ORGANIZAÇÃO DO EVENTO</div><h1>{event.name}</h1><p className="inline-meta"><CalendarDays size={17}/>{dateText(event)}<Button variant="text" onClick={()=>ctx.setDialog({type:'event',eventId:event.id})}><Pencil size={14}/>Editar evento</Button></p></div><div className="export-wrap"><Button variant="secondary" onClick={()=>exportExcel(event.id)} disabled={ctx.exporting}><Download size={17}/>{ctx.exporting?'Exportando…':'Exportar este evento'}</Button><small>Inclui todos os itens e cotações, sem aplicar os filtros.</small></div></div>
 <Metrics events={[event]}/><section className="panel"><div className="panel-heading"><div><h2>Serviços e materiais <span className="count">{event.items.length}</span></h2><p>Organize os itens e escolha os orçamentos do evento.</p></div><Button onClick={()=>ctx.setDialog({type:'item',eventId:event.id,categoryId:category})}><Plus size={18}/>Adicionar item</Button></div>
 <div className="filters"><div className="search-field"><Search size={18}/><input aria-label="Buscar descrição ou fornecedor" placeholder="Buscar descrição ou fornecedor" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filtrar por categoria" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{event.categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select aria-label="Filtrar por situação" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas as situações</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="table-edit-help">No computador, clique na descrição ou na situação para editar. A confirmação aparece depois de salvar.</div>
 {groups.map(c=>{const items=filtered.filter(i=>i.categoryId===c.id),s=categorySummary(event,c);return <section className={'category-group '+(c.notApplicable?'not-applicable':'')} key={c.id}>
 <div className="category-header"><div><h3>{c.name}</h3><Badge>{s.status}</Badge></div><div><span className="category-total">{money(s.value)}{s.partial&&s.value!==null?' (parcial)':''}</span><Button variant="text" onClick={()=>ctx.setDialog({type:'category',eventId:event.id,categoryId:c.id})}><Settings2 size={16}/>Editar categoria</Button></div></div>
 {c.notApplicable&&<p className="category-message">Esta categoria não entra nos totais. Altere em “Editar categoria” se precisar incluí-la.</p>}
 {!items.length?<div className="category-empty"><span>{search||status?'Nenhum item corresponde à busca ou ao filtro.':c.notApplicable?'Nenhum item cadastrado.':'Comece adicionando um serviço ou material.'}</span>{!search&&!status&&<Button variant="text" onClick={()=>ctx.setDialog({type:'item',eventId:event.id,categoryId:c.id})}><Plus size={15}/>Adicionar item</Button>}</div>:<>
 <div className="table-scroll desktop-items"><table className="items-table"><thead><tr><th>Descrição</th><th>Fornecedor / contato</th><th>Qtd. / unidade</th><th>Valor unitário</th><th>Total escolhido</th><th>Situação</th><th>Valor pago</th><th>Saldo a pagar</th><th>Ações</th></tr></thead><tbody>{items.map(i=>{const q=selected(i),supplier=supplierFor(i);return <tr key={i.id} className={i.status==='Cancelado'?'canceled':''}>
 <td><InlineDescription item={i} busy={ctx.busy} onSave={value=>simpleSave(i,{description:value})}/>{i.notes&&<small className="item-note">{i.notes}</small>}<button className="plain-link detail-link" onClick={()=>details(i)}>Detalhes e cotações ({i.quotes.length})</button></td>
 <td>{supplier?.name??'Não informado'}<small>{supplier?[supplier.contact,supplier.phone].filter(Boolean).join(' · '):''}</small></td>
 <td>{!q||q.quantity===null?'Não informado':quantityInput(q.quantity)}<small>{i.unit}</small></td><td>{money(q?.unitPrice)}</td><td className="strong">{money(quoteTotal(q))}</td>
 <td><select className="inline-select" aria-label={'Situação de '+i.description} disabled={ctx.busy} value={i.status} onChange={e=>simpleSave(i,{status:e.target.value}).catch(()=>{})}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></td>
 <td>{money(i.paidCents)}</td><td>{money(i.status==='Contratado'&&i.paidCents!==null?quoteTotal(q)-i.paidCents:null)}</td><td><Button variant="text" onClick={()=>edit(i)}><Pencil size={15}/>Editar</Button></td></tr>;})}</tbody></table></div>
 <div className="mobile-items">{items.map(i=><article className="mobile-item" key={i.id}><div><h4>{i.description}</h4><Badge>{i.status}</Badge></div><p>{supplierFor(i)?.name??'Fornecedor não informado'}</p><div className="mobile-values"><span>Total escolhido<strong>{money(quoteTotal(selected(i)))}</strong></span><span>Valor pago<strong>{money(i.paidCents)}</strong></span></div><Button variant="secondary" onClick={()=>details(i)}>Detalhes e cotações<ChevronRight size={16}/></Button><Button variant="text" onClick={()=>edit(i)}>Editar item</Button></article>)}</div>
 </>}</section>;})}<div className="panel-bottom"><Button variant="text" onClick={()=>ctx.setDialog({type:'category',eventId:event.id})}><Plus size={17}/>Adicionar categoria</Button></div></section></>;
}
function Suppliers({ctx}){
 const [search,setSearch]=useState(''),suppliers=ctx.state.suppliers.filter(s=>[s.name,s.city,s.contact,s.categories.join(' ')].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <><div className="page-heading"><div><div className="eyebrow">SUA REDE DE CONTATOS</div><h1>Fornecedores</h1><p>Cadastre uma vez e reutilize em todas as formaturas.</p></div><Button onClick={()=>ctx.setDialog({type:'supplier'})}><Plus size={18}/>Cadastrar fornecedor</Button></div>
 <div className="panel"><div className="panel-heading"><div className="search-field"><Search size={18}/><input aria-label="Buscar fornecedor" placeholder="Buscar nome, cidade ou categoria" value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="subtle">{suppliers.length} fornecedores</span></div>
 {!suppliers.length?<Empty icon={Users} title={search?'Nenhum fornecedor encontrado':'Seus fornecedores começam aqui'} action={!search&&<Button onClick={()=>ctx.setDialog({type:'supplier'})}><Plus size={17}/>Cadastrar fornecedor</Button>}>{search?'Tente outro nome, cidade ou categoria.':'Guarde os contatos e tenha tudo à mão ao pedir um orçamento.'}</Empty>:<div className="supplier-list">{suppliers.map(s=><article className="supplier-card" key={s.id}><div className="supplier-avatar">{s.name.slice(0,2).toUpperCase()}</div><div className="supplier-main"><h3>{s.name}</h3><p>{[s.contact,s.city].filter(Boolean).join(' · ')||'Contato e cidade não informados'}</p><div className="supplier-contacts"><span>{s.phone||'Telefone não informado'}</span>{s.email&&<a href={'mailto:'+s.email}>{s.email}</a>}</div><div className="tags">{s.categories.map((c,i)=><span key={i}>{c}</span>)}</div>{s.notes&&<p className="supplier-notes">{s.notes}</p>}</div><div className="supplier-actions"><Button variant="secondary" onClick={()=>ctx.setDialog({type:'supplier',supplierId:s.id})}><Pencil size={15}/>Editar</Button><Button variant="text danger-text" onClick={()=>ctx.confirm('Excluir fornecedor?','O cadastro de “'+s.name+'” será excluído. Fornecedores ligados a cotações precisam ter o vínculo removido primeiro.',()=>ctx.act('supplier.delete',{id:s.id}))}><Trash2 size={15}/>Excluir</Button></div></article>)}</div>}</div></>;
}
function ItemDetails({event,item,ctx,onClose}){
 const [feedback,setFeedback]=useState(null),q=selected(item),supplier=ctx.state.suppliers.find(s=>s.id===q?.supplierId),total=quoteTotal(q),category=event.categories.find(c=>c.id===item.categoryId);
 async function attempt(action,data,success){try{await ctx.act(action,data);setFeedback({message:success,error:false});}catch(e){setFeedback({message:e.message,error:true});}}
 return <Modal title="Detalhes do item" onClose={onClose} wide busy={ctx.busy}><div className="dialog-body">
 <div className="detail-title"><div><span className="eyebrow">{category?.name}</span><h2>{item.description}</h2></div><Badge>{item.status}</Badge></div>
 {!isActive(event,item)&&<div className="notice">Este item está fora dos totais porque foi cancelado ou a categoria não se aplica.</div>}
 {feedback&&<div className={'notice '+(feedback.error?'danger':'')} role={feedback.error?'alert':'status'}>{feedback.message}</div>}
 <div className="detail-grid"><div><span>Fornecedor escolhido</span><strong>{supplier?.name??'Não informado'}</strong><small>{supplier?[supplier.contact,supplier.phone,supplier.email].filter(Boolean).join(' · '):''}</small></div><div><span>Total escolhido</span><strong>{money(total)}</strong><small>{!q||q.quantity===null?'Quantidade não informada':quantityInput(q.quantity)+' '+item.unit} · {money(q?.unitPrice)} por {item.unit}</small></div><div><span>Valor pago</span><strong>{money(item.paidCents)}</strong></div><div><span>Saldo a pagar</span><strong>{money(item.status==='Contratado'&&item.paidCents!==null?total-item.paidCents:null)}</strong></div></div>
 {item.notes&&<div className="detail-notes"><h3>Observações</h3><p>{item.notes}</p></div>}
 <div className="detail-actions"><Button variant="secondary" onClick={()=>ctx.setDialog({type:'item',eventId:event.id,itemId:item.id})}><Pencil size={16}/>Editar item</Button><Button variant="secondary" disabled={ctx.busy} onClick={()=>attempt('item.duplicate',{eventId:event.id,itemId:item.id},'Item duplicado, sem pagamentos. A cópia está na lista do evento.')}><Copy size={16}/>Duplicar item</Button>{item.status==='Contratado'&&<Button onClick={()=>ctx.setDialog({type:'pay',eventId:event.id,itemId:item.id})}><Wallet size={16}/>Registrar pagamento</Button>}</div>
 <div className="quotes-heading"><div><h3>Comparação de orçamentos</h3><p>Somente o orçamento escolhido entra nos totais.</p></div><Button variant="secondary" onClick={()=>ctx.setDialog({type:'quote',eventId:event.id,itemId:item.id})}><Plus size={16}/>Adicionar cotação</Button></div>
 {!item.quotes.length?<Empty icon={FileSpreadsheet} title="Nenhuma cotação cadastrada">Adicione cotações para comparar os fornecedores e escolher um orçamento.</Empty>:<div className="quotes">{item.quotes.map(quote=>{const chosen=quote.id===item.selectedQuoteId,s=ctx.state.suppliers.find(s=>s.id===quote.supplierId);return <article className={'quote-card '+(chosen?'chosen':'')} key={quote.id}><div className="quote-heading"><h4>{s?.name??'Fornecedor não informado'}</h4>{chosen&&<span className="chosen-label"><Check size={14}/>Escolhido</span>}</div><p>{s?[s.contact,s.phone].filter(Boolean).join(' · '):'Você pode informar o fornecedor depois.'}</p><strong className="quote-value">{money(quoteTotal(quote))}</strong><p>{quote.quantity===null?'Quantidade não informada':quantityInput(quote.quantity)+' '+item.unit} × {money(quote.unitPrice)}</p>{quote.notes&&<p className="quote-notes">{quote.notes}</p>}<div className="quote-actions">
 {chosen?<span className="subtle">Incluído no previsto quando o item está ativo</span>:<Button variant="secondary" disabled={ctx.busy} onClick={()=>attempt('quote.choose',{eventId:event.id,itemId:item.id,quoteId:quote.id},'Orçamento escolhido e salvo.')}>Escolher este orçamento</Button>}
 <div><Button variant="text" onClick={()=>ctx.setDialog({type:'quote',eventId:event.id,itemId:item.id,quoteId:quote.id})}>Editar cotação</Button><button className="icon-button danger-text" aria-label={'Excluir cotação de '+(s?.name??'fornecedor não informado')} onClick={()=>ctx.confirm('Excluir cotação?','Esta cotação será removida do item. Um contrato precisa manter um orçamento escolhido.',()=>ctx.act('quote.delete',{eventId:event.id,itemId:item.id,quoteId:quote.id}))}><Trash2 size={16}/></button></div></div></article>;})}</div>}
 </div><div className="dialog-footer"><Button variant="text danger-text" onClick={()=>ctx.confirm('Excluir item?','O item “'+item.description+'” e todas as suas cotações serão excluídos.',async()=>{await ctx.act('item.delete',{eventId:event.id,itemId:item.id});onClose();})}><Trash2 size={16}/>Excluir item</Button><Button variant="secondary" onClick={onClose}>Fechar detalhes</Button></div></Modal>;
}
export default function Workspace(){
 const [auth,setAuth]=useState(null),[state,setState]=useState(null),[initialError,setInitialError]=useState(''),[loading,setLoading]=useState(true);
 const [view,setView]=useState('overview'),[eventId,setEventId]=useState(''),[category,setCategory]=useState(''),[dialog,setDialog]=useState(null),[detail,setDetail]=useState(null);
 const [busy,setBusy]=useState(false),[exporting,setExporting]=useState(false),[toast,setToast]=useState(null),[confirmation,setConfirmation]=useState(null);
 const lock=useRef(false),timer=useRef(null),revision=useRef(null);
 function notify(message,kind='success'){setToast({message,kind});clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(null),kind==='error'?12000:4500);}
 function accept(data){revision.current=data.revision;setState(data);}
 async function loadData(user){setAuth({initialized:true,user});const data=await request('state');accept(data);if(!data.defaultYear&&data.events.some(e=>!e.year))setDialog({type:'year'});}
 async function boot(){setLoading(true);setInitialError('');try{const status=await request('auth/status');setAuth(status);if(status.user)await loadData(status.user);}catch(e){setInitialError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{boot();return()=>clearTimeout(timer.current);},[]);
 async function act(action,data){
 if(lock.current)throw new Error('Aguarde o salvamento atual antes de continuar.');lock.current=true;setBusy(true);
 try{const r=await request('mutate',{method:'POST',body:JSON.stringify({action,data,revision:revision.current})});accept(r.state);notify('Alterações salvas.');return r;}
 catch(e){if(e.status===409){try{accept(await request('state'));}catch{}}if(e.status===401){setState(null);setAuth(a=>({...a,user:null}));setDialog(null);setDetail(null);setConfirmation(null);}throw e;}finally{lock.current=false;setBusy(false);}
 }
 async function exportExcel(id){
 setExporting(true);try{const res=await fetch('/api/export'+(id?'?eventId='+encodeURIComponent(id):''));if(!res.ok){const data=await res.json();throw new Error(data.error||'Não foi possível exportar.');}
 const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=id?'formatura.xlsx':'formaturas-completo.xlsx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);notify('Excel exportado com todos os registros do escopo escolhido.');
 }catch(e){notify(e.message,'error');}finally{setExporting(false);}
 }
 function navigate(next){setView(next);setEventId('');setCategory('');}
 function open(id,cat=''){setView('events');setEventId(id);setCategory(cat);}
 async function signOut(){try{await request('auth/logout',{method:'POST',body:'{}'});setState(null);setAuth(a=>({...a,initialized:true,user:null}));setDialog(null);setDetail(null);setConfirmation(null);}catch(e){notify(e.message,'error');}}
 const ctx={state,busy,exporting,act,setDialog,setDetail,notify,confirm:(title,message,action)=>setConfirmation({title,message,action})};
 if(loading)return <div className="loading-page"><GraduationCap size={38}/><LoaderCircle size={22} className="spin"/><p>Carregando suas formaturas…</p></div>;
 if(!auth?.user||!state)return <Auth auth={auth} onAuthenticated={loadData} onRetry={boot} error={initialError}/>;
 const current=state.events.find(e=>e.id===eventId),dialogEvent=state.events.find(e=>e.id===dialog?.eventId),dialogItem=dialogEvent?.items.find(i=>i.id===dialog?.itemId),detailEvent=state.events.find(e=>e.id===detail?.eventId),detailItem=detailEvent?.items.find(i=>i.id===detail?.itemId);
 return <div className="app-shell"><aside className="sidebar"><button className="brand" onClick={()=>navigate('overview')}><div><GraduationCap size={26}/></div><span>Organização de<strong>Formaturas</strong></span></button>
 <span className="nav-label">SEU PLANEJAMENTO</span><nav aria-label="Navegação principal">{[['overview','Visão geral',LayoutDashboard],['events','Eventos',CalendarDays],['suppliers','Fornecedores',Users]].map(([key,label,Icon])=><button key={key} className={view===key?'active':''} aria-current={view===key?'page':undefined} onClick={()=>navigate(key)}><Icon size={20}/>{label}{key==='events'&&<span>{state.events.length}</span>}</button>)}</nav>
 <div className="sidebar-bottom"><div className="sidebar-help"><FileSpreadsheet size={23}/><strong>Do planejamento à celebração</strong><p>Seus contatos e custos sempre organizados.</p></div><button className="account" onClick={signOut}><span className="avatar">{auth.user.email.slice(0,1).toUpperCase()}</span><span><strong>Administrador</strong><small>{auth.user.email}</small></span><LogOut size={17}/><span className="sr-only">Sair</span></button></div></aside>
 <div className="main-shell"><header className="topbar"><span>Formaturas<ChevronRight size={14}/>{view==='overview'?'Visão geral':view==='suppliers'?'Fornecedores':'Eventos'}</span><div className="topbar-actions"><Button variant="text" onClick={()=>setDialog({type:'year'})}><CalendarDays size={16}/>{state.defaultYear?'Ano '+state.defaultYear:'Ano a definir'}<Settings2 size={14}/></Button><button className="icon-button logout-mobile" aria-label="Sair" onClick={signOut}><LogOut size={17}/></button></div></header>
 <main>{view==='overview'?<Overview ctx={ctx} open={open} exportExcel={exportExcel}/>:view==='suppliers'?<Suppliers ctx={ctx}/>:current?<EventDetail key={current.id} event={current} category={category} setCategory={setCategory} ctx={ctx} back={()=>navigate('events')} exportExcel={exportExcel}/>:<><div className="page-heading"><div><div className="eyebrow">CADA CONQUISTA, UM EVENTO</div><h1>Eventos</h1><p>Abra uma formatura para organizar serviços, materiais e pagamentos.</p></div><Button onClick={()=>setDialog({type:'event'})}><Plus size={18}/>Cadastrar evento</Button></div><div className="event-grid">{state.events.map(e=><EventCard key={e.id} event={e} open={open}/>)}</div></>}</main><footer className="main-footer">Organização de Formaturas<span>Valores em reais · Datas no horário local</span></footer></div>
 {detailItem&&<ItemDetails event={detailEvent} item={detailItem} ctx={ctx} onClose={()=>setDetail(null)}/>}
 {dialog?.type==='supplier'&&<SupplierForm ctx={ctx} supplier={state.suppliers.find(s=>s.id===dialog.supplierId)} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='year'&&<YearForm ctx={ctx} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='event'&&<EventForm ctx={ctx} event={dialogEvent} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='category'&&dialogEvent&&<CategoryForm ctx={ctx} event={dialogEvent} category={dialogEvent.categories.find(c=>c.id===dialog.categoryId)} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='item'&&dialogEvent&&<ItemForm ctx={ctx} event={dialogEvent} item={dialogItem} categoryId={dialog.categoryId} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='quote'&&dialogItem&&<QuoteForm ctx={ctx} event={dialogEvent} item={dialogItem} quote={dialogItem.quotes.find(q=>q.id===dialog.quoteId)} onClose={()=>setDialog(null)}/>}
 {dialog?.type==='pay'&&dialogItem&&<PayForm ctx={ctx} event={dialogEvent} item={dialogItem} onClose={()=>setDialog(null)}/>}
 {confirmation&&<FormDialog title={confirmation.title} onClose={()=>setConfirmation(null)} busy={busy} submitLabel="Confirmar exclusão" onSubmit={async()=>{await confirmation.action();setConfirmation(null);}}><p className="form-intro">{confirmation.message}</p></FormDialog>}
 {toast&&<div className={'toast '+toast.kind} role={toast.kind==='error'?'alert':'status'}>{toast.kind==='error'?<Info size={20}/>:<CheckCircle2 size={20}/>}<span>{toast.message}</span><button aria-label="Fechar mensagem" onClick={()=>setToast(null)}><X size={17}/></button></div>}
 </div>;
}
